/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const incidents_Logic_Dont_Modify_Closed = require('./code/incidents-logic-dont-modify-closed');

class jwincidentapp02Srv extends LCAPApplicationService {
    async init() {

        this.before('UPDATE', 'Incidents', async (request) => {
            await incidents_Logic_Dont_Modify_Closed(request);
        });

        return super.init();
    }
}


module.exports = {
    jwincidentapp02Srv
};